<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Thu, 04 Feb 2016 15:58:40 +0000 by Proyx
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'pxvip_userInfoPane' => "Possui #dias# dias de vip",
 ); 
